### ISSUE TITLE
Unknown LLM setting

### ISSUE THREAD

**Issue by Maetes** [silvanmelchior/IncognitoPilot#36]
Hi try to run it with the 
```
-e LLM="gpt:gpt-3.5-turbo"
```

flag but it returns:
```
Unknown LLM setting: gpt:gpt-3.5-turbo
```

**Comment by silvanmelchior** [comment]
Hi, sorry, this is outdated in the docs. It should be `gpt-openai:gpt-3.5-turbo`.

Can you confirm it works? Then I will update the readme.

**Comment by Maetes** [comment]
Hey, this works. Great. Nice tool! Thank you!

**Comment by silvanmelchior** [comment]
Awesome!
